version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    target-branch: 'develop'

  # Enable version updates for Docker in the 'Docker' directory
  - package-ecosystem: 'docker'
    directory: 'Docker/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
    target-branch: 'develop'

  # Enable version updates for Maven (Java) dependencies in the root directory
  - package-ecosystem: 'maven'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
    target-branch: 'develop'

  # Enable version updates for Maven (Java) dependencies in a subdirectory
  - package-ecosystem: 'maven'
    directory: 'subdirectory/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'
    target-branch: 'develop'
