# Spring Boot Application Configuration

# Server Configuration
server:
  port: 8080

# Data Source Configuration
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/Product
    username: myuser
    password: bl@dg3r$$

  # JPA and Hibernate Settings
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Liquibase Configuration
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
