version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: bl@dg3r$$
    ports:
      - "27017:27017"
    volumes:
      - B:/MongoDBData:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: Franz
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - B:/KafkaData:/var/lib/kafka/data
    depends_on:
      - zookeeper

  postgres:
    image: postgres:latest
    container_name: PostgreSQL
    environment:
      POSTGRES_PASSWORD: bl@dg3r$$
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
    ports:
      - "5432:5432"
    volumes:
      - B:/PostgresData:/var/lib/postgresql/data

  mariadb:
    image: mariadb:latest
    container_name: MariDb
    environment:
      MARIADB_ROOT_PASSWORD: bl@dg3r$$
      MARIADB_DATABASE: mydatabase
      MARIADB_USER: myuser
      MARIADB_PASSWORD: bl@dg3r$$
    ports:
      - "3306:3306"
    volumes:
      - B:/MariaDBData:/var/lib/mysql

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: SQLServer
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: bl@dg3r$$
    ports:
      - "1433:1433"
    volumes:
      - B:/SQLServerData:/var/opt/mssql

  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: TestSpring
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: bl@dg3r$$
    depends_on:
      - postgres

volumes:
  db_data:
