name: Template Test Pipeline

on:
  # Trigger on pull_request on Develop branch
  pull_request:
    branches:
      ['develop']
    paths-ignore:
      ['docs/**']

jobs:
  # Job to build the Docker image without running tests
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build Docker Image without Running Tests
        run: docker build --target builder --build-arg SKIP_TESTS=true -t my-app:builder  -f template.Dockerfile .

  # Job to run the tests inside the Docker container
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests in Docker Container
        run: |
          docker build --target tester --build-arg SKIP_TESTS=false -t my-app:test -f template.Dockerfile .
          docker run --rm my-app:test

  # Job to create a pull request to the main branch if tests pass
  create-pr:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request to Main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth login --with-token <<< "${GITHUB_TOKEN}"
          gh pr create --base main --head develop --title "[Pull Request] Automated Testing Pull Request" --body "Automated PR created after successful tests Further Description added from previous commits: "
